[tools]
# There was a moment when Notion search API was broken
# It was fixed directly in react-notion-x dependency
# When trying to replace the dependency I tried to run
# $ brew install vips
# $ yarn add https://github.com/NotionX/react-notion-x#v6.16.2
# There's weird errors if one is building react-notion-x directly from github
# 'ValueError: invalid mode: 'rU' while trying to load binding.gyp'
# These should be fixed by downgrading python to 3.10
# Source: https://stackoverflow.com/a/74732671
python = ['3.10']

# The node-gyp module doesn't work properly when using node 20
# TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
# See more: https://stackoverflow.com/a/77910474/1337062
node = ['20']
"npm:pnpm" = '8.11.0'
